# Generated by Django 3.1.7 on 2021-03-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incometype')),
            ],
        ),
    ]
