# Generated by Django 3.1.7 on 2021-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_income_incometype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalsaving',
            old_name='amount',
            new_name='in_bank',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalsaving',
            name='in_cash',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalsaving',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
