# Generated by Django 3.1.7 on 2021-03-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210307_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToPay',
            new_name='MoneyBorrowed',
        ),
        migrations.RenameModel(
            old_name='YouLended',
            new_name='MoneyLended',
        ),
    ]
