# Generated by Django 3.1.7 on 2021-03-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210317_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyborrowed',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moneylended',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='moneyborrowed',
            name='date_borrowed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moneyborrowed',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moneylended',
            name='collection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moneylended',
            name='date_lended',
            field=models.DateField(),
        ),
    ]
