# Generated by Django 3.1.7 on 2021-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210317_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyborrowed',
            name='returned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='moneylended',
            name='collected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
